name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.1.3
  - pytest=7.4.4
  - scipy=1.15.3
  - pip=23.3.1
  - databricks-cli=0.18.0
  - numpy=1.26.4
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
