name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml=6.0.2
  - hydra-core=1.3.2
  - pip=23.3.1
  - networkx=3.4.2
  - databricks-cli=0.18.0
  - pyarrow=11.0.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
