name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.5.2
  - pyarrow
  - networkx=3.2.1
  - pytest=7.4.4
  - scipy=1.13.1
  - omegaconf=2.3.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
