name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - hydra-core=1.3.2
  - matplotlib=3.9.4
  - pandas=2.1.3
  - pip=25.0.1
  - scikit-learn=1.6.1
  - databricks-cli=0.18.0
  - numpy=1.26.4
  - pyarrow=11.0.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
